#!/bin/bash
# Point every generated boot configuration at a real server address.
#
#   bash render-configs.sh 192.168.1.5            # rewrite configs
#   bash render-configs.sh 192.168.1.5 --serve    # ...and start a test HTTP server
#   bash render-configs.sh 192.168.1.5 --tftp-first # warm-reboot-safe UEFI
#
# The address is where the client will fetch filesystem.squashfs over HTTP. It
# does not have to be the same box as the TFTP server.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SERVER="${1:-}"
MODE="${2:-}"

# This script ships in two places: the repository's pxe/ directory, and the
# generated tree in out/pxe. Only the generated tree has boot files to rewrite,
# so if we were started from the source copy, work on the generated one instead.
# Getting this wrong leaves {{HTTP}} unsubstituted, and the client then tries to
# fetch its root filesystem from a host literally named "{{HTTP}}".
if [ -f "$HERE/pxelinux.cfg/default" ]; then
    PXE="$HERE"
elif [ -f "$HERE/../out/pxe/pxelinux.cfg/default" ]; then
    PXE="$(cd "$HERE/../out/pxe" && pwd)"
    echo "  (using the generated tree at $PXE)"
else
    echo "No PXE tree found. Run build/build.sh first." >&2
    exit 1
fi

if [ -z "$SERVER" ]; then
    echo "usage: bash render-configs.sh <server-ip-or-host[:port]> [--serve|--tftp-first]" >&2
    exit 1
fi

# Validate before interpolating into sed or touching any boot menu. A URL,
# whitespace, or sed metacharacter here otherwise produces a broken boot tree.
if [[ ! "$SERVER" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*(:[0-9]{1,5})?$ ]]; then
    echo "HTTP address must be an IPv4 address or DNS hostname with an optional port." >&2
    exit 1
fi
if [[ "$SERVER" == *:* ]]; then
    PORT="${SERVER##*:}"
    if (( 10#$PORT < 1 || 10#$PORT > 65535 )); then
        echo "HTTP port must be between 1 and 65535." >&2
        exit 1
    fi
fi
case "$MODE" in
    ""|--serve|--tftp-first) ;;
    *) echo "Unknown rendering option: $MODE" >&2; exit 1 ;;
esac

# The HTTP address may include a port. NFS roots and DHCP next-server values
# cannot, so keep the host portion separately for those protocols. This helper
# intentionally accepts IPv4 addresses and ordinary DNS hostnames; bracketed
# IPv6 URLs are not generated by the build today.
SERVER_HOST="${SERVER%%:*}"
HOST_NAME="${SERVER_HOST%.}"
if [ "${#HOST_NAME}" -gt 253 ] || [[ "$SERVER_HOST" == *..* ]]; then
    echo "Invalid HTTP server hostname." >&2
    exit 1
fi
IFS=. read -r -a HOST_LABELS <<< "$HOST_NAME"
for label in "${HOST_LABELS[@]}"; do
    if [ "${#label}" -gt 63 ] || [[ ! "$label" =~ ^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?$ ]]; then
        echo "Invalid HTTP server hostname label." >&2
        exit 1
    fi
done
if [[ "$HOST_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    for octet in "${HOST_LABELS[@]}"; do
        if [ "${#octet}" -gt 3 ] || (( 10#$octet > 255 )); then
            echo "Invalid HTTP server IPv4 address." >&2
            exit 1
        fi
    done
fi

changed=0
for f in "$PXE/pxelinux.cfg/default" "$PXE/grub/grub.cfg" "$PXE/boot.ipxe"; do
    [ -f "$f" ] || continue
    if grep -q '{{HTTP}}' "$f"; then
        sed -i "s|nfsroot={{HTTP}}:|nfsroot=$SERVER_HOST:|g; s|{{HTTP}}|$SERVER|g" "$f"
        changed=$((changed + 1))
    fi
    # Templates can contain both placeholders and previously rendered entries.
    # Retarget both, and propagate write failures to the deployment caller.
    sed -i -E "s|(http://)[^/[:space:]]+|\1$SERVER|g; \
               s|\(http,[^)]+\)|(http,$SERVER)|g; \
               s|(nfsroot=)[^:[:space:]]+(:[0-9]+)?(:/srv/thinclient)|\1$SERVER_HOST\3|g" \
        "$f"
    echo "  updated    ${f#$PXE/}"
done
[ "$changed" -gt 0 ] || echo "  (configs had already been rendered - addresses refreshed)"

if [ "$MODE" = "--tftp-first" ] && [ -f "$PXE/grub/grub.cfg" ]; then
    # A few UEFI NICs retain enough state across a warm reboot for TFTP to work
    # but time out on GRUB's first TCP/HTTP connection. Loading the kernel and
    # initrd over TFTP gives Linux a clean NIC reset; the much larger squashfs
    # still uses HTTP. Keep the HTTP entry as the automatic fallback.
    if grep -q '/thinclient/lite/' "$PXE/grub/grub.cfg"; then
        # Dual-profile trees list the three HTTP choices first. Entry 3 is the
        # equivalent Lite Auto Cache TFTP path. Since it is now the selected
        # path, describe it as restart-safe and recommended instead of calling
        # the default a recovery option. The other TFTP entries remain recovery
        # choices because they are not selected automatically.
        sed -i \
            -e 's/^set default=.*/set default=3/' \
            -e 's/^set fallback=.*/set fallback=0/' \
            -e 's/^set timeout=.*/set timeout=2/' \
            -e 's/^menuentry "Lite Auto Cache - HTTP fast path (recommended)" {$/menuentry "Lite Auto Cache - HTTP fast path" {/' \
            -e 's/^menuentry "Lite Auto Cache - TFTP recovery" {$/menuentry "Lite Auto Cache - restart-safe (recommended)" {/' \
            "$PXE/grub/grub.cfg"
    else
        sed -i \
            -e 's/^set default=.*/set default=1/' \
            -e 's/^set fallback=.*/set fallback=0/' \
            -e 's/^set timeout=.*/set timeout=1/' \
            -e 's/^menuentry "\(Start .*\) - HTTP fast path (recommended)" {$/menuentry "\1 - HTTP fast path" {/' \
            -e 's/^menuentry "\(Start .*\) - TFTP recovery" {$/menuentry "\1 - restart-safe (recommended)" {/' \
            "$PXE/grub/grub.cfg"
    fi
    echo "  selected   grub TFTP kernel/initrd first (HTTP fallback)"
fi

cat <<EOF

Serve these over TFTP + HTTP:

  TFTP root  : $PXE
  HTTP root  : $PXE          (so /thinclient/filesystem.squashfs resolves)

  DHCP option 66 (next-server) : <TFTP server IP; no port>
  DHCP option 67 (boot file)   : pxelinux.0                    BIOS clients
                                 grub/x86_64-efi/core.efi      UEFI, Secure Boot off
                                 bootx64.efi                   UEFI, Secure Boot on

If the UEFI loaders are missing, run:  sudo bash $PXE/make-uefi-netboot.sh
EOF

if [ "$MODE" = "--serve" ]; then
    echo
    echo "serving $PXE on http://0.0.0.0:8080/ - Ctrl+C to stop"
    cd "$PXE"
    exec python3 -m http.server 8080
fi
